import type { AuditReport } from "./input.js";
const escape = (value: string) => value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);
export function renderReport(report: AuditReport): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Website audit · ${escape(report.id)}</title><style>
  :root{font-family:system-ui,sans-serif;color:#16312a;background:#f2f5f2}body{max-width:1060px;margin:48px auto;padding:0 24px}h1{font-size:40px;letter-spacing:-1px}h2{margin-top:0}header p{overflow-wrap:anywhere;color:#52665e}.eyebrow{font-size:12px;letter-spacing:3px;font-weight:700}.stats{display:flex;gap:12px;flex-wrap:wrap;margin:28px 0}.stats span,section{background:white;border:1px solid #d9e3dc;border-radius:16px;padding:20px}.stats span{flex:1;min-width:110px}section{margin:24px 0}ul{padding:0;list-style:none}li{padding:14px 0;border-top:1px solid #e6ece8;overflow-wrap:anywhere}li p{margin:8px 0 0;color:#52665e}.badge{font-size:12px;font-weight:700;margin-right:12px}.pass{color:#13704b}.fail{color:#b52d32}.unknown{color:#946a00}img{display:block;max-width:100%;height:auto;border:1px solid #d9e3dc;border-radius:8px;margin:20px auto}details{margin-top:18px;overflow-wrap:anywhere}footer{font-size:13px;color:#52665e;line-height:1.7}code{font-size:12px}
  </style></head><body><header><p class="eyebrow">KITE · WEBSITE ACCEPTANCE</p><h1>${report.outcome === "passed" ? "Checks passed" : report.outcome === "issues_found" ? "Issues found" : "Review required"}</h1><p>${escape(report.url)}</p><p>${escape(report.createdAt)} · ${(report.durationMs / 1000).toFixed(1)} seconds · ${escape(report.id)}</p></header><div class="stats"><span><b>${report.summary.passed}</b> passed</span><span><b>${report.summary.failed}</b> failed</span><span><b>${report.summary.unknown}</b> inconclusive</span></div>
  ${report.viewports.map((v) => `<section><h2>${escape(v.viewport)} · ${v.width} × ${v.height}</h2><ul>${v.checks.map((c) => `<li><span class="badge ${c.status}">${c.status.toUpperCase()}</span><b>${escape(c.label)}</b><p>${escape(c.detail)}</p></li>`).join("")}</ul><details><summary>Browser evidence</summary><ul>${[...v.errors, ...v.failedRequests.map((r) => `${r.reason} · ${r.url}`)].map((s) => `<li><code>${escape(s)}</code></li>`).join("") || "<li>No captured errors.</li>"}</ul></details><img alt="${escape(v.viewport)} viewport screenshot" src="data:image/jpeg;base64,${v.screenshot.base64}"></section>`).join("")}
  <footer><b>Scope and limitations</b><ul>${report.limitations.map((s) => `<li>${escape(s)}</li>`).join("")}</ul><p>This report is a point-in-time observation, not a security or accessibility certification.</p></footer></body></html>`;
}
